name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # Tests with a 32-bit container.
  check-i386:
    name: 32-bit container check for ${{ matrix.bin }}${{ matrix.nthreads && format(' -w{0}', matrix.nthreads) || '' }}
    runs-on: ubuntu-latest
    container:
      image: i386/debian:11.5
    strategy:
      fail-fast: false
      matrix:
        include:
          - {bin: form}
          - {bin: tform}
          - {bin: tform, nthreads: 2}
    steps:
      # We have to use v1.
      # See https://github.com/actions/checkout/issues/334
      - name: Checkout repository
        uses: actions/checkout@v1

      - run: ls
