name: Test

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-24.04}
          - {os: ubuntu-24.04-arm}
          - {os: macos-14}
          - {os: macos-15}
          - {os: macos-15-intel}
          - {os: macos-26}
    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd
          mktemp a.XXXXXXXXXX
          ls
          mkdir build
          mktemp build/b.XXXXXXXXXX
          ls build
